[package]
authors = ["Matthias Endler <matthias-endler.de>"]
description = "A glorious link checker"
documentation = "https://github.com/lycheeverse/lychee/blob/master/README.md"
edition = "2018"
homepage = "https://github.com/lycheeverse/lychee"
license = "Apache-2.0/MIT"
name = "lychee"
repository = "https://github.com/lycheeverse/lychee"
version = "0.3.1"

[dependencies]
anyhow = "1.0.37"
futures = "0.3.8"
glob = "0.3.0"
http = "0.2.2"
hubcaps = "0.6.2"
linkify = "0.4.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
regex = "1.4.2"
url = "2.2.0"
check-if-email-exists = "0.8.17"
indicatif = "0.15.0"
structopt = "0.3.21"
toml = "0.5.8"
serde = { version = "1.0.118", features = ["derive"] }
pulldown-cmark = "0.8.0"
quick-xml = "0.20.0"
headers = "0.3.2"
derive_builder = "0.9.0"
deadpool = "0.7.0"

[dependencies.reqwest]
features = ["gzip"]
version = "0.11.0"

[dependencies.tokio]
features = ["full"]
version = "1.0.1"

[dev-dependencies]
wiremock = "0.4.3"
assert_cmd = "1.0.2"
predicates = "1.0.6"
