[workspace]
members = [
    "lychee-bin",
    "lychee-lib",
]

[patch.crates-io]
# Switch back to version on crates.io after 0.6.3+ is released
hubcaps = { git="https://github.com/softprops/hubcaps.git" }
