[package]
name = "lychee"
authors = ["Matthias Endler <matthias@endler.dev>"]
description = "A glorious link checker"
documentation = "https://github.com/lycheeverse/lychee/blob/master/README.md"
edition = "2018"
homepage = "https://github.com/lycheeverse/lychee"
keywords = [
    "link",
    "checker",
    "cli",
    "link-checker",
    "validator",
]
license = "Apache-2.0/MIT"
repository = "https://github.com/lycheeverse/lychee"
version = "0.6.0"

[dependencies]
lychee-lib = { path = "../lychee-lib", version = "0.6.0", default-features = false }
anyhow = "1.0.40"
console = { version = "0.14.1" }
headers = "0.3.4"
http = "0.2.4"
indicatif = { version = "0.15.0", optional = true }
openssl-sys = "0.9.61"
regex = "1.4.5"
reqwest = { version = "0.11.3", features = ["gzip"] }
# Make build work on Apple Silicon.
# See https://github.com/briansmith/ring/issues/1163
# This is necessary for the homebrew build
# https://github.com/Homebrew/homebrew-core/pull/70216
ring = "0.16.20"
serde = { version = "1.0.125", optional = true, features = ["derive"] }
serde_json = { version = "1.0.64", optional = true }
structopt = "0.3.21"
tokio = { version = "1.5.0", features = ["rt", "sync", "test-util"] }
toml = { version = "0.5.8", optional = true }

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = { version = "1.0.7", default-features = false }
pretty_assertions = "0.7.1"
tempfile = "3.2.0"
tokio = { version = "1.5.0", features = ["macros"] }
uuid = { version = "0.8.2", features = ["v4"] }
wiremock = "0.5.2"

[features]
# Full experience
default = ["config_file", "json_output", "indicatif"]
# Accept config file in TOML format
config_file = ["serde", "toml"]
# Support JSON as output format
json_output = ["lychee-lib/serde", "serde", "serde_json"]
vendored-openssl = ["lychee-lib/vendored-openssl", "openssl-sys/vendored"]
